# docker-compose.yml

# Specifies the Docker Compose file format version.
version: "3.8"

# Defines the services (containers) that make up your application.
services:
  # The name of our service. You can call it anything (e.g., 'app', 'api').
  backend:
    # Tells Docker Compose to build the image from the Dockerfile in the current directory ('.').
    build: .
    # Sets a friendly name for the running container.
    container_name: swift-resume-api
    # Maps port 5001 on your computer to port 5001 inside the container.
    ports:
      - "5001:5001"
    # Mounts the 'uploads' folder from your computer into the container for persistent storage.
    volumes:
      - ./uploads:/usr/src/app/uploads
    # Specifies a file to read environment variables from. This is the BEST PRACTICE.
    env_file:
      - .env
    # Ensures the container restarts automatically if it crashes.
    restart: unless-stopped
