import { Schema, model, Document, Types } from "mongoose";

/**
 * @interface IPlan
 * Represents a subscription plan document in the database.
 * This stores the mapping between your internal plans and Razorpay's plans.
 */
export interface IPlan extends Document {
  _id: Types.ObjectId;
  name: string; // A user-friendly name (e.g., "Monthly", "Quarterly")
  cashfreePlanId: string; // The plan ID generated by Razorpay
  price: number; // Price in the smallest currency unit (e.g., paise for INR)
  durationMonths: number; // The duration of the plan in months
  createdAt: Date;
  updatedAt: Date;
}

const planSchema = new Schema<IPlan>(
  {
    name: {
      type: String,
      required: true,
    },
    cashfreePlanId: {
      type: String,
      required: true,
      unique: true, // create a unique index on the new field
      index: true,
    },
    price: {
      type: Number,
      required: true,
    },
    durationMonths: {
      type: Number,
      required: true,
    },
  },
  {
    timestamps: true,
  }
);

export default model<IPlan>("Plan", planSchema);
